### ISSUE TITLE
Thank you! 

### ISSUE THREAD

**Issue by denisidoro** [magneticchen/Daijishou#18]
Hey! I just wanted to thank you for your hard work.

I've been searching for a free game front-end for a while and it seems that Daijishou is gonna be my daily driver.

Dig is very limited. Pegasus is unusable to me because scraping is too cumbersome.

With custom players I can even add games from my PC and remotely launch them using Tasker.

I have some minor comments. I don't expect you to work on them or anything. It's just my 2 cents:
- I haven't been able to set platform wallpapers. They seem to be ineffective
- clicking on the platform wallpaper could be equivalent to "play library" (it's easier to click a large rectangle than click that small button)
- the home page could fill the whole screen. I have a rather vertical phone and the sides are just empty space. The button bar is scrollable but it wouldn't be if all space was used
- the platform screen could have a gallery view similar to "Highlights", in addition to the vertical list view
- The error message "Java.lang.exception: no description found" could be revisited
- The scraper was able to find descriptions for 95% of my games, but it found boxarts for only ~20% or so. Perhaps you could add a fallback scraper to get missing data?

Anyway, thanks again. Feel free to close this issue once you read it!

**Comment by Retro-Devils** [comment]
Whoa launching stuff thru Tasker.  And I love to launch sh files thru termux and weird stuff like that

**Comment by magneticchen** [comment]
- I haven't been able to set platform wallpapers. They seem to be ineffective

I've tried it again on my devices and work. May Be sure to click save button after setting up wallpaper. If the problem is not resolved did it showed any error? Or could you provide some footage.

- clicking on the platform wallpaper could be equivalent to "play library" (it's easier to click a large rectangle than click that small button)

Thanks for the suggestions. Have added in version 134.

- the home page could fill the whole screen. I have a rather vertical phone and the sides are just empty space. The button bar is scrollable but it wouldn't be if all space was used
the platform screen could have a gallery view similar to "Highlights", in addition to the vertical list view

Currently, the platforms page width is decided by aspect ratio which is set as "2:1". I've tried several wider options and it doesn't looks good. Maybe make it as a configurable option?

- The error message "Java.lang.exception: no description found" could be revisited

True.

- The scraper was able to find descriptions for 95% of my games, but it found boxarts for only ~20% or so. Perhaps you could add a fallback scraper to get missing data?

For me with filenames of my roms it scans roughly 80%. Was planned to add checksum scan but still finding good sources can rule them all for it. Currently IGDB is my option.

**Comment by denisidoro** [comment]
> wallpaper

My bad... I forgot to click on "save", apparently. It's working now!

**Comment by denisidoro** [comment]
> screen ratio

FYI, I just updated the app and I real estate is much better now. Thanks!
