### ISSUE TITLE
Some Dreamcast games is not being imported

### ISSUE THREAD

**Issue by jonatastrafaniuc** [magneticchen/Daijishou#332]
Some Dreamcast games are not being imported to library after sync. The same games appears and runs directly from emulator redream.
I checked files and folder names and not found any problem, including permissions and visibility.
Already tried remove, re-add and re-sync and still not showing up.

The games are:
- Daytona
- Marvel vs Capcom 2

Folders:
![BD2A7F97-5DDD-48D2-ACB7-EDA997F2E60F](https://user-images.githubusercontent.com/23291565/227208451-0b7f161e-d6ab-4371-b23b-2e05d81a8074.jpeg)
![8107F1F2-6E97-4A1B-8363-FCB270A7BAD0](https://user-images.githubusercontent.com/23291565/227208470-f674448d-a728-4390-a196-46d5f387204d.jpeg)
![A4CFA07F-0262-40F0-BF45-3D768580EDC6](https://user-images.githubusercontent.com/23291565/227208488-4ba90d8a-bc2d-4142-9e3b-6b91d73fa151.jpeg)

Daijishou:
![76B6CF0D-A11C-495B-A8AF-F0F1F9DA9254](https://user-images.githubusercontent.com/23291565/227209500-fc52d1c9-6737-400d-9aeb-affe13be11b2.jpeg)

redream emulator:
![31A0BAC5-3E64-4F5B-84EA-82FD91B68EB4](https://user-images.githubusercontent.com/23291565/227210327-87805f8b-6cdc-4807-8b5d-1a1ac64fcc26.jpeg)

**Comment by Jetup13** [comment]
The games are being recognized as the same so they are being skipped over by Daijishou. Check the contents of the gdi file's (with a notepad editor) and you'll notice that they are exactly the same. If the contents are the same then it will produce the same md5 hash. Reason why they are the same is because of the naming of the bin and raw files are the same for your roms.

> List of fixes:

1. Convert the games to chd. You can use [chdman](https://github.com/Jetup13/Retroid-Pocket-3-Plus-Wiki/wiki/Useful-Programs#chdman) or [namDHC](https://github.com/Jetup13/Retroid-Pocket-3-Plus-Wiki/wiki/Useful-Programs#namdhc) to do this for you
2. Or rename track1 to something else and update the gdi file to reflect the change
3. Or use a redump romset as they have proper naming schemes to avoid this

**Comment by jonatastrafaniuc** [comment]
Since I am not on PC, the second option (renaming track1 then updating gdi file) solved the problem. Thank you!

Maybe this issue can be avoided by adding the gdi file name to the hash calculation in future releases.
