### ISSUE TITLE
Cannot load files from NAS Share

### ISSUE THREAD

**Issue by RobotLimeLtd** [magneticchen/Daijishou#385]
When I try to launch a rom from a NAS share via Daijishō (using an Retroarch 64 core), I get the error: 

`This item no longer exists on the analysed file path, required by “{file.path}” in “am start” argument`

I can load these same games from the NAS just fine from Retroarch 64 itself so not sure why Daijishō is throwing an error.  After granting Files & Media and NAS permissions to Daijishō, I was able to find the NAS-hosted roms and sync them, so it feels like this isn’t a permissions error.

Btw, my game files are on a NAS Share so that I can access the same set of games from several devices (another Shield TV, a Retropie, etc).  I have an nVidia Shield TV with Retroarch 64 installed (from apk) and Daijishō (also installed from apk).

**Comment by magneticchen** [comment]
Retroarch requires absolute path as the parameter to launcher the file. However, file on NAS doesn't have the path with respect of local filesystem. Therefore launch from NAS is not possible. 

You can try the player with `{file.uri}` argument.

**Comment by Sp33dFr34k** [comment]
@RobotLimeLtd did you ever find a workaround? Have the exact same situation and issue...

**Comment by Sian-Lee-SA** [comment]
This is the only thing that I'm critical over this app... Everything was exactly how I wanted my front-end to be then find out that it wont pass the path to RetroArch. Changing to file.uri just results in loading RetroArch to a black screen... Tried other emulators eg. ePSXe, M64 and PPSSPP and they worked fine even though they're on the network share. This might indicate that it is more of a RetroArch issue than Daijishou but could also be a simple Intent param unfortunately there's not much noise on this issue to help find a solution.

Now that this has been marked as won't fix, then I think it's time to help and move towards an open source front-end

**Comment by Sian-Lee-SA** [comment]
Turns out using the -e ROM /storage/{share-name}/path/rom/file,zip works with RetroArch... I just edited the player for RetroArch to point to a specific rom file and loaded without problems. Need a {file.name} variable to get the file name only which we can then hardcode the path and append the file name. This will probably be more involved if someone has roms in sub folders etc. though

**Comment by rcostanza** [comment]
Just adding to this, as I'm also trying to find a workaround. I'm running Daijishou on an Nvidia Shield, that has a native network share mount feature, and having my ROMs on a network share.

I did the same test as above and hardcoded the "user friendly path" `/storage/<share name>/<path to the rom>` to a ROM on the mounted network share to the RetroArch intent used to launch from Daijishou, and it worked. So that's the thing, it has to pass that path, not the URI/URL.

I inspected that ROM's file details using X-plore File Manager on Android and it was able to show me both URL and path, so in theory it's possible to form/retrieve the path RetroArch requires.

**Comment by rcostanza** [comment]
I came up with a very basic Android app that converts the `file.uri` to a path RetroArch will accept. Tested on an Nvidia Shield TV where the NAS can be mounted to a friendly `/storage/<share name>` path, but could work with other solutions.

https://github.com/rcostanza/daijishou_nas_fix

Kind of a pain to set up, but it works.
