### ISSUE TITLE
Player arguments for Citra MMJ

### ISSUE THREAD

**Issue by Aetavicus** [magneticchen/Daijishou#67]
I had issues launching 3ds ROMs from Daijisho using Citra MMJ as it was coming out with Invalid ROM file errors.
What solved this is changing the parameters in Player arguments for "org.citra.emu - antutu" from "-e GamePath {file.path}" to "-e GamePath {file.uri}". After this, I can launch the 3ds ROMs just fine. 

Would be great if this is set to default or documented down somewhere.

**Comment by magneticchen** [comment]
Sorry. But I have dropped out citra updating support. Too many repeating requests everywhere asking the same questions. Because citra at this point has too much app generations, forks and versions. And inconsistent behaviours even with the exact same app. I made the conclusion that the fragmentations are not manageable by myself.
