### ISSUE TITLE
Portrait / Vertical Screen Support.

### ISSUE THREAD

**Issue by Marvin626** [magneticchen/Daijishou#97]
Hello, i have been using Daijisho for a good time now, and i got to say it is indeed a godsend for emulation on a cellphone.

theres definitely some things that do keep it from being 100% perfect tho, one of them, at least from my point of view is for the frontend to be compatible with vertical displays or to be usable in portrait mode, as well as landscape.

now, while i am aware that landscape/horizontal is kind of the standard for anyone who uses emulators, im sure theres people who are more used to vertical displays rather than horizontals. on my case, i made this micro bartop arcade project that uses a cellphone as its core , think a 'DIY Icade', that at least design wise requires for the cellphone to be set vertical. right now i am using a force rotation app to use Daijisho with the setup i have, but of course, that is not the best choice since a) the frontend is not really well designed for vertical displays by default, leading to options that cant be seen, inverted controls, among others, and b) in order to use the force rotation app, you NEED to have a rooted phone, which not many people have and its getting more and more harder to do.

hopefully theres a way to make this a possibility, thanks in advance.

**Comment by magneticchen** [comment]
Hello. A few people have purposed the idea to allow Dai in vertical mode. However, daijishou is designed to be in landscape and with hotkeys in mind. Under the constraints the UI can be consistent and adaptive in ranges of screen sizes.

**Comment by AdityaMH** [comment]
Look good
![IMG_20230326_045849](https://user-images.githubusercontent.com/33791472/227744717-afc14187-1791-4862-acfd-0a450954d75d.jpg)

**Comment by ppvnf** [comment]
@AdityaMH yes,it does. it is just a mockup,right?

**Comment by AdityaMH** [comment]
> @AdityaMH yes,it does. it is just a mockup,right?

actually no. i can doing this using pip app

**Comment by AdityaMH** [comment]
> daijishou is designed to be in landscape and with hotkeys

funfact your hotkeys doesn't support to my joystick or keyboard. i can't go back, cancel, or shortcut.
everything i press is only lead to "OK".
Also only can moving object and meow meow.

**Comment by ElsamMarura** [comment]
So, to test this, I decompiled the APK, edited a few lines in the AndroidManifest.xml, and rebuilt the APK. Now, Daijishou runs in all orientation modes. The only UI issue I encountered was that I need to find a wallpaper pack that fits all orientations (of course, lol). Additionally, the list mode in the library doesn't show the right side of the UI. However, Daijishou in portrait mode actually looks great.

I also had to uninstall my original Daijishou because it had a different signature than the modified one, which caused me to lose all my settings. I couldn't restore the backup from Google Drive—maybe because of the different signature? (Not sure)

@TapiocaFox, you should reconsider this, as some of us, especially those using tablets, prefer playing in portrait mode. Maybe you could add this as an experimental feature option that isn't enabled by default.

<img src="https://github.com/user-attachments/assets/f9350676-58ac-452e-972c-6dee1b1b3d49" width=25% height=25%>
<img src="https://github.com/user-attachments/assets/0403e76c-a219-44c0-9f0d-3f63791241b7" width=25% height=25%>
<img src="https://github.com/user-attachments/assets/3ed6698c-1052-4335-8065-458001b9b115" width=25% height=25%>

**Comment by zakiur** [comment]
This would be a really great feature to use with an 8bitdo mobile gaming clip and micro controller. Dig has a similar feature where under orientation you can use Smartboy which cover half of the screen in vertical mode and sticks the front end to the top half of the screen.

**Comment by AdityaMH** [comment]
But, i think this launcher only for retro handheld and dev never do thing for mobile phone. So your hope will be never reached.

**Comment by mmlmrx** [comment]
I would vote for this feature as well, as it is more comfortable to use a tablet with a gamepad in portrait mode than it is to use it in landscape mode.
